CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER(10) NOT NULL
    GOODSNAME VARCHAR2(40)
    PRICE NUMBER(10)
    CATEGORY_ID NUMBER(10)
);

CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER(10) NOT NULL
    GATEGORY_NAME VARCHAR2(20)
);

CREATE TABLE SALE (
    
)